version: '3'

services:
  # nginx:
  #   build:
  #       context: .
  #       dockerfile: ./compose/server/Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - frontend
  #     - backend
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Secret_admin@2019'
      MYSQL_DATABASE: 'trcobao'
      MYSQL_USER: 'octavio'
      MYSQL_PASSWORD: 'secret@2019'
    volumes:
      - db-trcobao:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    command: npm run serve
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - 8080:8080
volumes:
  db-trcobao: